spring:
  profiles:
    active: mysql
---
spring:
  profiles: mysql
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          highlight_sql: true
          #        format_sql: true
          show_sql: true
          jdbc:
            lob:
              non_contextual_creation: true
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
config:
  domain: {}
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
naver-app:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
---
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
##  security:
##    oauth2:
##      client:
##        registration:
##          google:
##            client-id: ${GOOGLE_CLIENT_ID}
##            client-secret: ${GOOGLE_CLIENT_SECRET}
##            scope:
##              - email
##              - profile
#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: TRACE
#      springframework:
#        orm:
#          jpa: DEBUG
#server:
#  servlet:
#    encoding:
#      force-response: true
#
#mail:
#  address:
#    admin: admin@gmail.com
#jwt:
#  key: ${JWT_SECRET_KEY}
#  access-token-expiration-minutes: 30
#  refresh-token-expiration-minutes: 420
