export const health = [
  {id: 1, title: "영양보충", src: `${process.env.PUBLIC_URL}/images/healthicons/nutrition.png`},
  {id: 2, title: "눈건강", src: `${process.env.PUBLIC_URL}/images/healthicons/eye.png`},
  {id: 3, title: "면역력", src: `${process.env.PUBLIC_URL}/images/healthicons/shield.png`},
  {id: 4, title: "간건강", src: `${process.env.PUBLIC_URL}/images/healthicons/liver.png`},
  {id: 5, title: "피로회복", src: `${process.env.PUBLIC_URL}/images/healthicons/power.png`},
  {id: 6, title: "장건강", src: `${process.env.PUBLIC_URL}/images/healthicons/intestine.png`},
  {id: 7, title: "체지방감소", src: `${process.env.PUBLIC_URL}/images/healthicons/weight.png`},
  {id: 8, title: "혈행개선", src: `${process.env.PUBLIC_URL}/images/healthicons/blood.png`},
  {id: 9, title: "피부건강", src: `${process.env.PUBLIC_URL}/images/healthicons/moisture.png`},
  {id: 10, title: "위건강", src: `${process.env.PUBLIC_URL}/images/healthicons/stomach.png`},
  {id: 11, title: "관절/뼈건강", src: `${process.env.PUBLIC_URL}/images/healthicons/bone.png`},
  {id: 12, title: "갱년기", src: `${process.env.PUBLIC_URL}/images/healthicons/menopause.png`},
  {id: 13, title: "기억력개선", src: `${process.env.PUBLIC_URL}/images/healthicons/brain.png`},
  {id: 14, title: "긴장완화", src: `${process.env.PUBLIC_URL}/images/healthicons/relax.png`},
  {id: 15, title: "성장발육", src: `${process.env.PUBLIC_URL}/images/healthicons/grow.png`},
  {id: 16, title: "혈당조절", src: `${process.env.PUBLIC_URL}/images/healthicons/bloodsugar.png`},
  {id: 17, title: "혈압조절", src: `${process.env.PUBLIC_URL}/images/healthicons/heart-rate.png`},
  {id: 18, title: "항산화", src: `${process.env.PUBLIC_URL}/images/healthicons/cell.png`},
  {id: 19, title: "전립선", src: `${process.env.PUBLIC_URL}/images/healthicons/prostate.png`},
  {id: 20, title: "콜레스테롤", src: `${process.env.PUBLIC_URL}/images/healthicons/cholesterol.png`},
]